name: "Deploy website"
on:
  push:
    branches: [main]

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout landing page
        uses: actions/checkout@v3
        with:
          repository: br-g/openf1-landing-page
          token: ${{ secrets.LANDING_PAGE_TOKEN }}
          path: landing-page

      - name: Build Slate documentation
        run: |
          mkdir -p ${{ github.workspace }}/build/docs
          docker run --rm \
          --user $(id -u):$(id -g) \
          --name slate \
          -v ${{ github.workspace }}/build/docs:/srv/slate/build \
          -v ${{ github.workspace }}/documentation:/srv/slate/source \
          slatedocs/slate build

      - name: Copy landing page
        run: |
          cp ${{ github.workspace }}/landing-page/index.html build/
          cp ${{ github.workspace }}/landing-page/contact.html build/

      - name: Copy additional webpages
        run: |
          cp ${{ github.workspace }}/documentation/pages/* build

      - name: Deploy documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
